export type JobRoleId = "FRONTEND" | "BACKEND" | "FULLSTACK";
export type LevelId = "BEGINNER" | "JUNIOR" | "MIDDLE" | "SENIOR";

export const JOB_ROLES: { id: JobRoleId; label: string }[] = [
  { id: "FRONTEND", label: "프론트엔드" },
  { id: "BACKEND", label: "백엔드" },
  { id: "FULLSTACK", label: "풀스택" },
];

export const LEVELS: { id: LevelId; label: string; sub: string }[] = [
  { id: "BEGINNER", label: "입문자", sub: "1년 미만" },
  { id: "JUNIOR", label: "주니어", sub: "1~3년차" },
  { id: "MIDDLE", label: "미들", sub: "3~5년차" },
  { id: "SENIOR", label: "시니어", sub: "5년차 이상" },
];

export const LEVEL_COLORS: Record<LevelId, string> = {
  BEGINNER: "bg-emerald-500/30 bg-emerald-500/10 text-emerald-400",
  JUNIOR: "bg-blue-500/30 bg-blue-500/10 text-blue-400",
  MIDDLE: "bg-amber-500/30 bg-amber-500/10 text-amber-400",
  SENIOR: "bg-red-500/30 bg-red-500/10 text-red-400",
};

/** 이력서·프로필 기술 선택 모달에 사용되는 그룹(자주 쓰이는 순·대표 라인업 확장). */
export const TAG_GROUPS = [
  {
    label: "프론트엔드",
    tags: [
      "React",
      "Next.js",
      "Remix",
      "Vue",
      "Nuxt.js",
      "Svelte",
      "Angular",
      "TypeScript",
      "JavaScript",
      "Webpack",
      "Vite",
      "Tailwind CSS",
      "shadcn/ui",
      "Radix UI",
      "Storybook",
      "React Query",
      "TanStack Query",
      "Zustand",
      "Redux",
      "Vuex",
      "Pinia",
      "Apollo Client",
      "GraphQL",
      "Relay",
      "WebSocket",
      "WebRTC",
      "Framer Motion",
      "Styled Components",
      "CSS Modules",
      "Sass",
      "HTML",
      "CSS",
      "Responsive Design",
    ],
  },
  {
    label: "모바일",
    tags: [
      "React Native",
      "Flutter",
      "Kotlin",
      "Swift",
      "Jetpack Compose",
      "SwiftUI",
      "iOS",
      "Android",
    ],
  },
  {
    label: "백엔드 · API",
    tags: [
      "Java",
      "Spring Boot",
      "Spring Security",
      "Spring MVC",
      "Spring Cloud",
      "Kotlin",
      "Node.js",
      "Express",
      "NestJS",
      "Fastify",
      "Python",
      "Django",
      "FastAPI",
      "Flask",
      "Go",
      "Gin",
      "Rust",
      "Actix",
      "Ruby",
      "Ruby on Rails",
      ".NET",
      "ASP.NET Core",
      "C#",
      "REST API",
      "gRPC",
      "GraphQL (Server)",
      "Protobuf",
      "OpenAPI",
    ],
  },
  {
    label: "데이터베이스",
    tags: [
      "PostgreSQL",
      "MySQL",
      "MariaDB",
      "SQLite",
      "MongoDB",
      "Redis",
      "Elasticsearch",
      "OpenSearch",
      "DynamoDB",
      "Cassandra",
      "CockroachDB",
      "Neo4j",
    ],
  },
  {
    label: "인프라 · DevOps",
    tags: [
      "Docker",
      "Kubernetes",
      "Terraform",
      "Ansible",
      "AWS",
      "GCP",
      "Azure",
      "Nginx",
      "CDN",
      "Linux",
      "CI/CD",
      "GitHub Actions",
      "GitLab CI",
      "Jenkins",
      "Argo CD",
      "Helm",
      "Prometheus",
      "Grafana",
      "ELK Stack",
      "OpenTelemetry",
    ],
  },
  {
    label: "메시지 · 스트림",
    tags: ["Kafka", "RabbitMQ", "NATS", "AWS SQS", "AWS SNS", "PostgreSQL NOTIFY"],
  },
  {
    label: "데이터 · ML",
    tags: [
      "PyTorch",
      "TensorFlow",
      "scikit-learn",
      "Pandas",
      "NumPy",
      "Apache Spark",
      "Airflow",
      "dbt",
      "BigQuery",
      "Snowflake",
    ],
  },
  {
    label: "기타",
    tags: [
      "Git",
      "알고리즘",
      "자료구조",
      "보안",
      "테스트",
      "JUnit",
      "Jest",
      "Vitest",
      "Pytest",
      "Cypress",
      "Playwright",
      "Selenium",
      "AI/ML",
      "OAuth2",
      "JWT",
      "WebAssembly",
      "SSE",
      "국제화 i18n",
    ],
  },
];

export const SUGGESTED_TAGS: string[] = TAG_GROUPS.flatMap((group) => group.tags);
